// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYFR_0fLv986H661qJFcnC21RXmZq6b2U',
    appId: '1:949758032845:web:96771d26057cb35b4e2284',
    messagingSenderId: '949758032845',
    projectId: 'lifetrack-f9a8f',
    authDomain: 'lifetrack-f9a8f.firebaseapp.com',
    databaseURL: 'https://lifetrack-f9a8f-default-rtdb.firebaseio.com',
    storageBucket: 'lifetrack-f9a8f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-_roOs929UeXqBFNsXElzzuwBqsYKzw8',
    appId: '1:949758032845:android:ecbf3fa66e44141a4e2284',
    messagingSenderId: '949758032845',
    projectId: 'lifetrack-f9a8f',
    databaseURL: 'https://lifetrack-f9a8f-default-rtdb.firebaseio.com',
    storageBucket: 'lifetrack-f9a8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ-Bs1T8Aynscmj_da-VPdW_uZkih_33E',
    appId: '1:949758032845:ios:f703ece4aa250b924e2284',
    messagingSenderId: '949758032845',
    projectId: 'lifetrack-f9a8f',
    databaseURL: 'https://lifetrack-f9a8f-default-rtdb.firebaseio.com',
    storageBucket: 'lifetrack-f9a8f.firebasestorage.app',
    iosBundleId: 'com.example.lifeTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ-Bs1T8Aynscmj_da-VPdW_uZkih_33E',
    appId: '1:949758032845:ios:f703ece4aa250b924e2284',
    messagingSenderId: '949758032845',
    projectId: 'lifetrack-f9a8f',
    databaseURL: 'https://lifetrack-f9a8f-default-rtdb.firebaseio.com',
    storageBucket: 'lifetrack-f9a8f.firebasestorage.app',
    iosBundleId: 'com.example.lifeTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYFR_0fLv986H661qJFcnC21RXmZq6b2U',
    appId: '1:949758032845:web:eb6cea2e1d6389664e2284',
    messagingSenderId: '949758032845',
    projectId: 'lifetrack-f9a8f',
    authDomain: 'lifetrack-f9a8f.firebaseapp.com',
    databaseURL: 'https://lifetrack-f9a8f-default-rtdb.firebaseio.com',
    storageBucket: 'lifetrack-f9a8f.firebasestorage.app',
  );
}
