// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD18q1QzphyevNn8ebHyMMZXHykuE8uHsM',
    appId: '1:1085716807284:web:9a4a5e7ad5e364bcb61b21',
    messagingSenderId: '1085716807284',
    projectId: 'lab12firebas',
    authDomain: 'lab12firebas.firebaseapp.com',
    storageBucket: 'lab12firebas.firebasestorage.app',
    measurementId: 'G-BRH1CPVX26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDC8W88ntb1qd7bJ-Q32xHOUeL6ZGpVuME',
    appId: '1:1085716807284:android:7b1f6b2a4e4019bab61b21',
    messagingSenderId: '1085716807284',
    projectId: 'lab12firebas',
    storageBucket: 'lab12firebas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb0cQlaycQkpleawqyk5w7MylOaR3JHkg',
    appId: '1:1085716807284:ios:8cb2a81754bf7699b61b21',
    messagingSenderId: '1085716807284',
    projectId: 'lab12firebas',
    storageBucket: 'lab12firebas.firebasestorage.app',
    iosBundleId: 'com.example.lab12Firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb0cQlaycQkpleawqyk5w7MylOaR3JHkg',
    appId: '1:1085716807284:ios:8cb2a81754bf7699b61b21',
    messagingSenderId: '1085716807284',
    projectId: 'lab12firebas',
    storageBucket: 'lab12firebas.firebasestorage.app',
    iosBundleId: 'com.example.lab12Firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD18q1QzphyevNn8ebHyMMZXHykuE8uHsM',
    appId: '1:1085716807284:web:0f71f9239ab3cb9cb61b21',
    messagingSenderId: '1085716807284',
    projectId: 'lab12firebas',
    authDomain: 'lab12firebas.firebaseapp.com',
    storageBucket: 'lab12firebas.firebasestorage.app',
    measurementId: 'G-2Q2L5BVFMV',
  );
}
