// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA49QrNj4oayzu99CLoTQwo-Rz2rhZ7yd0',
    appId: '1:927706360730:web:1f3ce4b5e996b3b7d7e823',
    messagingSenderId: '927706360730',
    projectId: 'lab13firebase-a45e7',
    authDomain: 'lab13firebase-a45e7.firebaseapp.com',
    storageBucket: 'lab13firebase-a45e7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2wnncXkFjANVqHNLukiMVtLyTKZxlU5E',
    appId: '1:927706360730:android:dfd954934dcebe0fd7e823',
    messagingSenderId: '927706360730',
    projectId: 'lab13firebase-a45e7',
    storageBucket: 'lab13firebase-a45e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5FNZWDgVEr0UXqVtfF7T-0Il4VwWyaE4',
    appId: '1:927706360730:ios:9e02d281857c1c96d7e823',
    messagingSenderId: '927706360730',
    projectId: 'lab13firebase-a45e7',
    storageBucket: 'lab13firebase-a45e7.firebasestorage.app',
    iosBundleId: 'com.example.lab13AuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5FNZWDgVEr0UXqVtfF7T-0Il4VwWyaE4',
    appId: '1:927706360730:ios:9e02d281857c1c96d7e823',
    messagingSenderId: '927706360730',
    projectId: 'lab13firebase-a45e7',
    storageBucket: 'lab13firebase-a45e7.firebasestorage.app',
    iosBundleId: 'com.example.lab13AuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA49QrNj4oayzu99CLoTQwo-Rz2rhZ7yd0',
    appId: '1:927706360730:web:0e6e422e6479f535d7e823',
    messagingSenderId: '927706360730',
    projectId: 'lab13firebase-a45e7',
    authDomain: 'lab13firebase-a45e7.firebaseapp.com',
    storageBucket: 'lab13firebase-a45e7.firebasestorage.app',
  );
}
